import os
import psycopg2

DATABASE_URL = os.environ["DATABASE_URL"]

PRODUCTOS = [
    "ARROZ MELOSO CON PULPO",
    "ARROZ NEGRO CON CHIPIRONES Y LANGOSTINOS AHUMADOS",
    "BONDIOLA A LA CERVEZA NEGRA",
    "BROCOLIS Y COLIFLOR AHUMADOS CON ALIÑO DE OLIVA Y AZAFRAN",
    "CANELONES DE ESPINACA Y SALMON CON CREMA DE FINAS HIERBAS",
    "CORDERO CON SALSA DE SIRAH Y CHOCOLATE",
    "COSTILLAR A LA LEÑA",
    "COUS COUS CRIOLLO",
    "CREPPES DE CORDERO BRESEADO CON SALSA DE TOMATE NATURAL",
    "DHAL DE LENTEJAS ROJAS",
    "FINGER RIBS BARBACOA",
    "GRATEN DE CALABAZAS Y CHAMPIGNONES",
    "LASAGNA DE CARNE BRESEADA Y ESPINACAS",
    "LOMO A LA PIMIENTA",
    "MILANESA DE LOMO",
    "MOLLEJAS AHUMADAS CON PESTO DE RUCULA",
    "OSOBUCO AL MALBEC",
    "PAPAS BRAVAS CON PIMENTON AHUMADO",
    "PAPA HASSELBACK",
    "PAPINES AL AJILLO",
    "PECHUGUINES GRILLE",
    "PENNE RIGATE NEGRO CON FRUTOS DE MAR",
    "PILAF DE QUINOA VEGANO",
    "PIMIENTOS RELLENOS CON CHOCLOS SALTEADOS CON GHEE Y AZAFRAN",
    "PULPO ASADO CON OLIVA, PIMENTON ESPAÑOL Y BRUNOISE DE ACEITUNAS NEGRAS",
    "PURE DE BATATAS CON ESPECIAS Y MIEL",
    "PURE DE CALABAZA",
    "PURE DE PAPAS",
    "RATATUILLE",
    "RISOTTO CON MIX DE HONGOS Y VEGETALES AHUMADOS",
    "ROULE DE MERLUZA NEGRA , ESPARRAGOS AHUMADOS CON FUMET DE ENELDO Y LEMON GRASS",
    "SALMON ROSADO A LA MANTECA DE HIERBAS",
    "SPAGUETTIS CON SALSA DE TOMATES NATURALES",
    "TERRINA DE CORAZON DE ALCAUCILES Y ESPARRAGOS",
    "TORTILLA A LA ESPAÑOLA",
    "TORTILLA DE PAPA",
    "TRUCHA A LA MANTECA NEGRA Y ALCAPARRAS",
    "VEGETALES ASADOS",
    "WOK DE POLLO",
    "ZANAHORIAS NOISETTES GLASEADAS CON NARANJA, MIEL Y JENGIBRE",
    "ZUCHINNI CON CROUTE DE PROVOLONE",
]


def main():
    conn = psycopg2.connect(DATABASE_URL)
    cur = conn.cursor()
    for nombre in PRODUCTOS:
        cur.execute(
            "INSERT INTO productos (nombre, unidad, stock) VALUES (%s, 'unidades', 0) ON CONFLICT (nombre) DO NOTHING",
            (nombre,),
        )
    conn.commit()
    cur.close()
    conn.close()
    print(f"Listo: {len(PRODUCTOS)} productos verificados/cargados.")


if __name__ == "__main__":
    main()
